# Generated by Django 2.1.7 on 2019-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branches',
            field=models.CharField(default='', max_length=255),
        ),
    ]
