# Generated by Django 2.1.7 on 2019-03-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190313_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
