# Generated by Django 2.1.7 on 2019-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commitId', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('branchName', models.CharField(default='', max_length=255)),
                ('userEmail', models.CharField(default='', max_length=255)),
                ('pathToPatch', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MergeConflicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitId1', models.CharField(max_length=255)),
                ('commitId2', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('mergeDiffPath', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('owner', models.CharField(default='', max_length=255)),
                ('git_url', models.CharField(max_length=255, unique=True)),
                ('project_dir', models.CharField(max_length=255)),
                ('master_branch', models.CharField(max_length=255)),
                ('branches', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
