# Generated by Django 2.1.7 on 2019-03-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_auto_20190329_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
